# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title = "youngspe"
author = "Spencer Young"
description = """
Spencer Young's portfolio and blog
"""
url = "https://youngspe.github.io" # the base hostname & protocol for your site, e.g. http://example.com
future = true
timezone = "America/Los_Angeles"
date-format = "%B %-d, %Y"

plugins = ["jekyll-seo-tag", "jekyll-sass-converter", "jekyll-paginate-v2"]

exclude = ["node_modules/"]

baseurl = ""                                         # the subpath of your site, e.g. /blog
permalink = "/:categories/:year-:month-:day-:title/"

[[header-links]]
path = "about-me.mty"

[[contact]]
[contact.github]
user = "youngspe"

[[contact]]
[contact.linkedin]
user = "spencerwyoung"

[pagination]
enabled = true
per_page = 16
sort_field = "date"
sort_reverse = true
title = ":title"
permalink = ":num.html"

[pagination.trail]
before = 3 # The number of links before the current page
after = 3  # The number of links after the current page

[autopages]
enabled = true

[autopages.categories]
permalink = "/:cat"
layouts = ["home.mty"]
title = "category: :cat"

[autopages.tags]
permalink = "/tags/:tag"
layouts = ["home.mty"]
title = "tag: :tag"
